/* PocketPal - LCD renderer for the home screen and cut-scenes (hatch, evolve, death).
 * Canvas is 216x160 LCD pixels; pals are drawn at 3x (96px), FX at 2x. */
(function (root) {
  'use strict';
  var PP = root.PP = root.PP || {};
  var S = PP.Sprites, F = PP.Font;
  /* Home screen layout (LCD pixels). Everything keeps a safe margin from the LCD's
   * rounded edges: the bottom text ends 9 px above the bottom edge. */
  var W = 216, H = 160, PET = 3, PS = 32 * PET;
  /* 1.9.4: the LCD layout stays 216 x 160 'LCD pixels', but the canvas backing store is DPR x5 finer so the
   * 80 px sprite cells show every pixel: the pet (96 LCD px) is exactly 6x its 80 px cell, a Match card sprite
   * (48 LCD px) exactly 3x. Text, icons and boxes are drawn in LCD pixels and look exactly as before. */
  var DPR = 5;
  /* 1.8.4: the status strip has two rows (strip, strip2); stripEnd = the first free row under it. */
  var L = { topText: 2, topLine: 11, strip: 14, strip2: 23, stripH: 7, stripEnd: 31, ground: 136, floorLine: 140, bottomText: 144, textH: 7 };
  var GROUND = L.ground;
  var C = { ink: '#0f380f', dark: '#306230', mid: '#8bac0f', bg: '#9bbc0f', lite: 'rgb(206,224,110)' };

  function clear(ctx, col) { ctx.fillStyle = col || C.bg; ctx.fillRect(0, 0, W, H); }
  function dotted(ctx, y) { ctx.fillStyle = C.dark; for (var x = 0; x < W; x += 2) ctx.fillRect(x, y, 1, 1); }
  function clockText(st) { return PP.Time.clock(PP.Game.now(st), st.settings.clock || PP.Time.defaultClock(), { lcd: true }); }

  function statusBar(ctx, app, t) {
    var st = app.state, p = PP.Game.active(st);
    F.draw(ctx, clockText(st), 3, L.topText, C.ink);
    if (p && p.stage !== 'egg' && !p.fate) {
      F.draw(ctx, PP.Pet.formName(p).toUpperCase(), W / 2 + 8, L.topText, C.ink, 1, 'center');
      if (st.settings.test && st.settings.speed > 1) F.draw(ctx, 'x' + st.settings.speed, p.hard ? W - 34 : W - 16, L.topText, C.dark, 1, 'right');
      if (p.hard) F.draw(ctx, 'HARD', W - 3, L.topText, C.ink, 1, 'right');   // 1.9.0 hard-mode badge
      // 1.8.4: the flashing "!" call moved into the status strip (row 2), next to the other "right now" icons
    }
    dotted(ctx, L.topLine);
  }

  /* ---- compact status strip under the clock (1.8.4: two rows)
   *  row 1: hunger hearts, happiness hearts, energy bolt + 4 pips, stage + age
   *  row 2: discipline flag + bar, weight ('WT' + LO / OK / HI), then only what applies now:
   *         sick, poop + count, ! needs attention, ZZ asleep (or moon at night), Zz tired */
  var MINI = {
    heart: ['.#.#.', '#####', '#####', '.###.', '..#..'],
    empty: ['.#.#.', '#.#.#', '#...#', '.#.#.', '..#..'],
    food:  ['...###.', '..#####', '..#####', '...###.', '..#....', '.#.....', '##.....'],
    food_fish:  ['.......', '...###.', '#.#####', '.####.#', '#.#####', '...###.', '.......'],   // 1.9.9 per-diet hunger glyphs
    food_honey: ['.....#.', '.####..', '.####..', '#######', '#######', '#######', '.#####.'],
    food_fruit: ['...#.#.', '...##..', '.##.##.', '#######', '#######', '#######', '.##.##.'],
    smile: ['..###..', '.#...#.', '#.#.#.#', '#.....#', '##...##', '.#####.', '..###..'],   // 1.9.2: a round smiley (the square one read as a die)
    poop:  ['...#...', '..##...', '.####..', '.#####.', '#######'],
    moon:  ['..###', '.##..', '##...', '##...', '##...', '.##..', '..###'],
    tired: ['####.....', '..#......', '.#..####.', '####..#..', '.....#...', '....####.', '.........'],  // 1.8.3: 'Zz' = low energy
    bolt:  ['...##', '..##.', '.##..', '#####', '..##.', '.##..', '##...'],                            // energy
    flag:  ['#......', '#####..', '######.', '#####..', '#......', '#......', '#......'],              // discipline
    sick:  ['.#####.', '#######', '##.#.##', '#######', '.#####.', '.#.#.#.', '.......'],              // sick (skull)
    attn:  ['##', '##', '##', '##', '..', '##', '##']                                                  // needs attention
  };
  /* 1.9.8: each MINI glyph also has a x5 version (PP.GLYPHS, generated by tools/hud_glyphs.py) drawn on the canvas's
   * x5 backing store - same LCD box, real curves. MINI stays as the fallback and as the layout reference. */
  function glyphOf(rows) { for (var k in MINI) if (MINI[k] === rows) return PP.GLYPHS && PP.GLYPHS.g[k]; return null; }
  function mini(ctx, rows, x, y, col) {
    var hd = glyphOf(rows), r, c;
    if (hd) {
      var K = PP.GLYPHS.K;
      for (var pass = 0; pass < 2; pass++) {             // glyph colour first, then the pale highlight
        ctx.fillStyle = pass ? C.lite : (col || C.ink);
        var want = pass ? 43 : 35;                       // '+' / '#'
        for (r = 0; r < hd.rows.length; r++) {
          var row = hd.rows[r];
          for (c = 0; c < row.length; c++) {
            var ch = row.charCodeAt(c);
            if (ch === want || (!pass && ch === 43)) {
              var c0 = c; while (c + 1 < row.length && (row.charCodeAt(c + 1) === ch)) c++;
              ctx.fillRect(x + c0 / K, y + r / K, (c - c0 + 1) / K, 1 / K);
            }
          }
        }
      }
      return;
    }
    ctx.fillStyle = col || C.ink;
    for (r = 0; r < rows.length; r++) for (c = 0; c < rows[r].length; c++) if (rows[r].charCodeAt(c) === 35) ctx.fillRect(x + c, y + r, 1, 1);
  }
  function stageAge(p) {
    if (p.stage === 'egg') return 'EGG';
    var label = { baby: 'BABY', child: 'CHILD', teen: 'TEEN', adult: 'ADULT' }[p.stage] || '';
    var min = p.ageMin || 0, age = min < 1440 ? Math.max(0, Math.floor(min / 60)) + 'H' : Math.min(999, Math.floor(min / 1440)) + 'D';
    return label + ' ' + age;
  }
  /* The strip as boxes [kind, x, width] - also used by the layout audit to prove nothing overlaps. */
  function weightKind(p) { return PP.Care.isOverweight(p) ? 'HI' : PP.Care.isUnderweight(p) ? 'LO' : 'OK'; }
  function energyPips(p) { return Math.max(0, Math.min(4, Math.ceil((p.energy || 0) / 25))); }
  function stripBoxes(p, night) {
    var b = [], y = L.strip, y2 = L.strip2;
    function row2(k, w, extra) { var q = { k: k, x: x2, w: w, y: y2 }; for (var e in extra || {}) q[e] = extra[e]; b.push(q); x2 += w + 3; return q; }
    var x2 = 40 + F.width('WT') + 3 + F.width('OK') + 5;
    if (p.stage !== 'egg') {
      b.push({ k: PP.DATA.foodOf(p.species).glyph, x: 3, w: 7 }, { k: 'hunger', x: 11, w: 23, n: p.hunger });   // 1.9.9: the pal's own food
      b.push({ k: 'smile', x: 38, w: 7 }, { k: 'happy', x: 46, w: 23, n: p.happy });
      b.push({ k: 'bolt', x: 74, w: 5 }, { k: 'energy', x: 81, w: 19, n: energyPips(p) });
      b.push({ k: 'flag', x: 3, w: 7, y: y2 }, { k: 'discipline', x: 11, w: 24, y: y2, n: Math.max(0, Math.min(100, Math.round(p.discipline || 0))) });
      // 1.9.2: weight in words - 'WT' + LO / OK / HI. The old glyphs (bar / empty square / ball) were unreadable, and a
      // kettlebell drawn at 7 px looked like a padlock.
      b.push({ k: 'weight', x: 40, w: F.width('WT'), y: y2, text: 'WT' }, { k: 'weightN', x: 40 + F.width('WT') + 3, w: F.width(weightKind(p)), y: y2, text: weightKind(p) });
      if (p.sick) row2('sick', 7);
      if (p.poop > 0) { row2('poop', 7); x2 -= 1; row2('poopN', F.width(String(p.poop)), { text: String(p.poop) }); }
      if (!p.fate && PP.Care.attention(p).length) row2('attn', 2);
      if (p.asleep) row2('zzz', F.width('ZZ'), { text: 'ZZ' });
      else if (night) row2('moon', 5);
      if (PP.Care.isTired(p)) row2('tired', 9);
    }
    var sa = stageAge(p), sw = F.width(sa);
    b.push({ k: 'stage', x: W - 3 - sw, w: sw, text: sa });
    b.forEach(function (q) { if (q.y == null) q.y = y; q.h = L.stripH; });
    return b;
  }
  function drawStrip(ctx, p, t) {
    var night = p.stage !== 'egg' && PP.Sleep.isNight(PP.Time.minuteOfDay(PP.Game.now(PP.App.state)), PP.Sleep.of(p));
    stripBoxes(p, night).forEach(function (q) {
      if (q.k === 'hunger' || q.k === 'happy') for (var i = 0; i < 4; i++) mini(ctx, i < q.n ? MINI.heart : MINI.empty, q.x + i * 6, q.y + 1, i < q.n ? C.ink : C.dark);
      else if (q.k === 'energy') for (var j = 0; j < 4; j++) {          // 4 pips, 25 energy each; they blink when tired
        var on = j < q.n, blink = PP.Care.isTired(p) && Math.floor(t / 500) % 2;
        ctx.fillStyle = on ? (blink ? C.dark : C.ink) : C.dark;
        if (on) ctx.fillRect(q.x + j * 5, q.y + 1, 4, 5);
        else { ctx.fillRect(q.x + j * 5, q.y + 1, 4, 1); ctx.fillRect(q.x + j * 5, q.y + 5, 4, 1); ctx.fillRect(q.x + j * 5, q.y + 1, 1, 5); ctx.fillRect(q.x + j * 5 + 3, q.y + 1, 1, 5); }
      } else if (q.k === 'discipline') {                                   // a small bar, 0-100 %
        ctx.fillStyle = C.ink; ctx.fillRect(q.x, q.y + 1, q.w, 1); ctx.fillRect(q.x, q.y + 5, q.w, 1); ctx.fillRect(q.x, q.y + 1, 1, 5); ctx.fillRect(q.x + q.w - 1, q.y + 1, 1, 5);
        ctx.fillRect(q.x + 1, q.y + 2, Math.round((q.w - 2) * q.n / 100), 3);
      } else if (q.k === 'attn') mini(ctx, MINI.attn, q.x, q.y, Math.floor(t / 400) % 2 ? C.dark : C.ink);
      else if (MINI[q.k]) mini(ctx, MINI[q.k], q.x, q.y + (q.k === 'poop' ? 2 : 0), (q.k === 'poop' && p.poop >= 2 || q.k === 'tired') && Math.floor(t / 500) % 2 ? C.dark : C.ink);
      else if (q.text) F.draw(ctx, q.text, q.x, q.y, q.k === 'stage' || q.k === 'weight' ? C.dark : C.ink);
    });
  }

  /* Tamagotchi-style attention icon: a flashing "!" box in the top-right corner. */
  function attentionIcon(ctx, x, y, t) {
    if (Math.floor(t / 400) % 2) { ctx.fillStyle = C.dark; ctx.fillRect(x, y + 1, 10, 9); return; }
    ctx.fillStyle = C.ink; ctx.fillRect(x, y + 1, 10, 9);
    ctx.fillStyle = C.lite; ctx.fillRect(x + 4, y + 2, 2, 4); ctx.fillRect(x + 4, y + 7, 2, 2);
  }
  var NEED_ICON = { hunger: 1, happy: 2, poop: 3, sick: 4, lights: 5, tantrum: 7 };
  /* Speech bubble next to the pal showing WHAT it wants (cycles through all needs). */
  function needBubble(ctx, needs, px, y, flip, t, species) {
    if (!needs.length || Math.floor(t / 500) % 4 === 3) return;
    var k = needs[Math.floor(t / 1500) % needs.length];
    var bx = flip ? px + 2 : px + PS - 24, by = Math.max(L.stripEnd + 2, y - 6);
    bx = Math.max(1, Math.min(W - 21, bx));
    ctx.fillStyle = C.ink; ctx.fillRect(bx, by, 20, 17); ctx.fillRect(bx + 1, by - 1, 18, 19);
    ctx.fillRect(flip ? bx + 14 : bx + 3, by + 18, 3, 3);   // tail
    S.drawIcon(ctx, k === 'hunger' ? PP.DATA.foodOf(species).icon : NEED_ICON[k], bx + 4, by + 3, 1);   // 1.9.9: hungry for ITS food
  }

  /* 1.9.8: where poop #i sits (LCD px, top-left of its x2 FX cell). Two side by side stay inside the LCD (tested). */
  function poopAt(i) { return [W - 44 + (i % 2) * 15, GROUND - 32 - Math.floor(i / 2) * 30]; }
  /* ------------------------------------------------------------ wandering */
  function walkerUpdate(app, p, dt, t) {
    var w = app.walker || (app.walker = { x: 50, dir: 1, tx: 50, until: 0 });
    var maxX = W - PS - (p.poop > 0 ? 42 : 4);
    if (w.x > maxX) w.x = maxX;
    var still = p.asleep || p.sick || app.anim || p.fate || p.stage === 'egg';
    if (still) return false;
    if (w.tx > maxX) w.tx = maxX;
    if (Math.abs(w.x - w.tx) < 0.5) {
      // arrived: do something (stand, look around, sit, yawn, scratch, mope, dance), then maybe another thing
      if (!w.arrived) { w.arrived = true; w.act = PP.Behave.pickIdle(p, Math.random(), Math.random()); w.act.t0 = t; w.until = t + w.act.dur; }
      if (t > w.until) {
        if (Math.random() < 0.35) { w.act = PP.Behave.pickIdle(p, Math.random(), Math.random()); w.act.t0 = t; w.until = t + w.act.dur; }
        else { w.tx = 4 + Math.random() * Math.max(1, maxX - 4); w.arrived = false; w.act = null; }
      }
      return false;
    }
    w.act = null;
    var step = Math.min(Math.abs(w.tx - w.x), Math.min(dt, 100) * (PP.Care.isTired(p) ? 0.009 : 0.018));   // tired pals plod
    w.dir = w.tx > w.x ? 1 : -1;
    w.x += step * w.dir;
    return true;
  }

  /* -> [pose, frame]. Face animation (blinks, chewing) and idle behaviours live here. */
  function petPose(p, app, moving, t) {
    if (app.anim) {
      var a = app.anim, el = t - a.t0;
      if (a.kind === 'eat') return PP.Behave.eatFrame(el, 220);
      if (a.kind === 'clean') return [el > a.dur * 0.6 ? 'happy' : el > a.dur * 0.25 ? 'surprised' : 'idle', Math.floor(t / 250)];
      if (a.kind === 'refuse') return ['refuse', Math.floor(el / 170)];
      if (a.kind === 'dance' || a.kind === 'cup') return ['dance', Math.floor(el / 260)];
      // 1.8.3 too tired to play: a slow head-shake, then a big yawn
      if (a.kind === 'tired') return el < 760 ? ['refuse', Math.floor(el / 190)] : ['yawn', el < 1500 ? 0 : 1];
      // medicine: a 'yuck' head-shake first, then relief (or still poorly)
      if (a.kind === 'med') return el < a.dur * 0.35 ? ['refuse', Math.floor(el / 150)] : [a.pose || 'happy', Math.floor(el / 250)];
      // scolded: flinch, then droop with a tear
      if (a.kind === 'scold') return el < 320 ? ['surprised', 1] : ['sad', 1 + Math.floor((el - 320) / 380) % 3];
      if (a.kind === 'sad') return el < 260 ? ['hurt', 1] : ['sad', Math.floor(el / 380)];
      if (a.kind === 'happy') return ['happy', Math.floor(el / 250)];
      if (a.kind === 'sick') return ['sick', Math.floor(el / 300)];
      // 1.9.1 good morning: still sleepy, a big yawn, then a happy stretch
      // 2.0.0: ... and finally turns to say hello (front view, smiling)
      if (a.kind === 'wake') return el < 800 ? ['sleepy', Math.floor(el / 400)] : el < 1900 ? ['yawn', el < 1350 ? 0 : 1] : ['front', 2];
      // 2.0.0 'look at you': tapped / greeted -> turns to face you, then smiles; praised -> a happy hop, then a smile at you
      if (a.kind === 'look') return ['front', PP.Behave.lookFrame(el, 900)];
      if (a.kind === 'praise') return el < 700 ? ['happy', Math.floor(el / 250)] : ['front', 2];
      if (a.kind === 'stillAsleep') return ['sleep', Math.floor(t / 700)];
      return [a.pose || a.kind, Math.floor(t / 500)];
    }
    var m = PP.Care.moodPose(p);
    if (m !== 'idle') return [m, Math.floor(t / 500)];
    if (moving) return ['walk', Math.floor(t / 250)];
    var w = app.walker, act = w && w.act, pose = 'idle', frame = Math.floor(t / 500);
    if (act) { pose = act.pose; frame = act.frameMs ? Math.floor((t - act.t0) / act.frameMs) : 0; }
    if (pose === 'front') frame = PP.Behave.lookFrame(t - act.t0, null);   // 2.0.0: open-eyed breathing only (2 = smile, 3 = blink)
    if (pose === 'idle' && PP.Care.isTired(p)) return ['bored', Math.floor(t / 1200)];   // 1.8.3: heavy, half-shut eyes
    // natural blinking every 2-6 s while standing or sitting
    if (pose === 'idle' || pose === 'sit' || pose === 'look' || pose === 'front') {
      if (!w.blinkAt) w.blinkAt = t + PP.Behave.nextBlinkGap(Math.random());
      var bf = PP.Behave.blinkFrame(t - w.blinkAt);
      if (t - w.blinkAt > PP.Behave.BLINK_MS) w.blinkAt = t + PP.Behave.nextBlinkGap(Math.random());
      else if (bf >= 0) return pose === 'sit' ? ['sit', bf === 1 ? 1 : 3] : pose === 'front' ? ['front', bf === 1 ? 3 : frame] : ['blink', bf];   // open > half > closed > half > open
    }
    return [pose, frame];
  }

  /* The egg always moves as ONE rigid piece: a gentle whole-sprite rock (1 px left/right),
   * and just before hatching a quick rock between properly rotated frames. */
  function drawEgg(ctx, species, t, fast, x, y) {
    var step = Math.floor(t / (fast ? 140 : 650)) % 4;
    if (fast) {
      var pose = step === 1 || step === 3 ? 'walk' : 'idle', f = step === 3 ? 0 : 1;
      S.draw(ctx, species, 'egg', pose, pose === 'walk' ? f : 0, x, y, PET);
    } else {
      var dx = step === 1 ? 1 : step === 3 ? -1 : 0;
      S.draw(ctx, species, 'egg', 'idle', 0, x + dx * PET, y, PET);
    }
  }

  /* ---- 1.9.0 home scene: time of day + the weather of the day, in light tones only so the
   * pal, text and icons keep full contrast. Static when the player prefers reduced motion. */
  var sceneForce = null;
  function reducedMotion() { try { return !!(root.matchMedia && root.matchMedia('(prefers-reduced-motion: reduce)').matches); } catch (e) { return false; } }
  var bowMemo = {};
  function dayWeather(st, now) {
    var r = PP.util.roll(st.seed, PP.Shop.dayOf(now), 'weather');
    return r < 0.18 ? 'rain' : r < 0.26 ? 'snow' : 'clear';      // the 1.9.0 day roll (snow chance unchanged)
  }
  function sceneInfo(st) {
    if (sceneForce) return sceneForce;
    var now = PP.Game.now(st), d = new Date(now), h = d.getHours() + d.getMinutes() / 60;
    var phase = h >= 5 && h < 7 ? 'dawn' : h >= 7 && h < 17.5 ? 'day' : h >= 17.5 && h < 19.5 ? 'dusk' : 'night';
    // 1.9.1: the sky follows the pal's mood (PP.Behave.weather), on top of the day's roll
    var base = dayWeather(st, now), w = PP.Behave.weather(PP.Game.active(st), base);
    var bow = PP.Behave.rainbow(bowMemo, w, Date.now()) && phase !== 'night';
    return { phase: phase, weather: w, base: base, rainbow: bow };
  }
  function hills(ctx) {
    var top = L.floorLine;
    ctx.fillStyle = C.lite;
    ctx.globalAlpha = 0.35;
    for (var x = 0; x < W; x++) {                       // two soft, wide hills on the horizon
      var hgt = Math.round(10 + 7 * Math.sin(x / 34 + 0.6) + 4 * Math.sin(x / 13 + 2));
      ctx.fillRect(x, top - hgt, 1, hgt);
    }
    ctx.globalAlpha = 1;
  }
  /* 1.9.8: fill a shape on the x5 backing grid (1/5 LCD px rows): inside(u, v) in LCD px. Each row is one run per
   * span, never overlapping, so translucent sky colours stay even. Used for the sun, moon, clouds and lightning. */
  var SUB = 5;
  function fshape(ctx, x0, y0, x1, y1, inside) {
    for (var j = Math.floor(y0 * SUB); j < Math.ceil(y1 * SUB); j++) {
      var v = (j + 0.5) / SUB, run = -1;
      for (var i = Math.floor(x0 * SUB); i <= Math.ceil(x1 * SUB); i++) {
        var on = i < Math.ceil(x1 * SUB) && inside((i + 0.5) / SUB, v);
        if (on && run < 0) run = i;
        else if (!on && run >= 0) { ctx.fillRect(run / SUB, j / SUB, (i - run) / SUB, 1 / SUB); run = -1; }
      }
    }
  }
  function inDisc(u, v, cx, cy, r) { return (u - cx) * (u - cx) + (v - cy) * (v - cy) <= r * r; }
  function inCap(u, v, ax, ay, bx, by, r) {
    var dx = bx - ax, dy = by - ay, L2 = dx * dx + dy * dy || 1e-9, k = Math.max(0, Math.min(1, ((u - ax) * dx + (v - ay) * dy) / L2));
    var ex = u - ax - k * dx, ey = v - ay - k * dy; return ex * ex + ey * ey <= r * r;
  }
  function drawScene(ctx, st, t) {
    var info = sceneInfo(st), top = L.stripEnd, bottom = L.floorLine, still = reducedMotion();
    var tt = still ? 0 : t;
    if (info.phase === 'dawn' || info.phase === 'dusk') {   // a glow low in the sky
      for (var i = 0; i < 4; i++) { ctx.fillStyle = 'rgba(206,224,110,' + (0.10 + i * 0.06) + ')'; ctx.fillRect(0, bottom - 54 + i * 10, W, 10); }
      ctx.fillStyle = 'rgba(206,224,110,0.55)';
      var sx = info.phase === 'dawn' ? 30 : W - 42;
      fshape(ctx, sx - 6.5, bottom - 26.5, sx + 6.5, bottom - 19, function (u, v) { return inDisc(u, v, sx, bottom - 19.5, 6.5); });   // 1.9.8: a smooth half sun
    } else if (info.phase === 'night') {
      ctx.fillStyle = 'rgba(48,98,48,0.16)'; ctx.fillRect(0, top, W, bottom - top);
      ctx.fillStyle = C.lite;
      for (var k = 0; k < 14; k++) {
        var stx = (k * 53 + 17) % (W - 8) + 4, sty = top + 4 + (k * 29) % 46;
        if (!still && (Math.floor(tt / 900) + k) % 5 === 0) continue;  // gentle twinkle
        ctx.fillRect(stx, sty, 1, 1);
      }
      ctx.fillStyle = 'rgba(206,224,110,0.9)';                          // crescent moon
      var mcx = W - 29.5, mcy = top + 12.5;                              // 1.9.8: a smooth crescent on the x5 grid
      fshape(ctx, mcx - 5.6, mcy - 5.6, mcx + 5.6, mcy + 5.6, function (u, v) { return inDisc(u, v, mcx, mcy, 5.5) && !inDisc(u, v, mcx + 3, mcy - 1, 4.3); });
    } else if (info.weather === 'sunny') {                               // 1.9.1 sunny: a sun with turning rays, one small cloud
      var sunX = W - 34, sunY = top + 16, rot = still ? 0 : Math.floor(tt / 700) % 2;
      ctx.fillStyle = 'rgba(206,224,110,0.95)';
      var scx = sunX + 0.5, scy = sunY + 0.5;                            // 1.9.8: a round sun and tapered rays on the x5 grid
      fshape(ctx, scx - 5.6, scy - 5.6, scx + 5.6, scy + 5.6, function (u, v) { return inDisc(u, v, scx, scy, 5.5); });
      ctx.fillStyle = RAIN;
      var rays = [];
      for (var ra = 0; ra < 8; ra++) { var ang = (ra + rot * 0.5) * Math.PI / 4; rays.push([scx + Math.cos(ang) * 7.4, scy + Math.sin(ang) * 7.4, scx + Math.cos(ang) * 10.2, scy + Math.sin(ang) * 10.2]); }
      fshape(ctx, scx - 11, scy - 11, scx + 11, scy + 11, function (u, v) { for (var q = 0; q < rays.length; q++) if (inCap(u, v, rays[q][0], rays[q][1], rays[q][2], rays[q][3], 0.6)) return true; return false; });
      cloud(ctx, Math.round(((tt / 500) % (W + 40)) - 20), top + 12, 0.6);
    } else {                                                             // day: slow clouds (more of them when cloudy)
      var n = info.weather === 'clear' || info.weather === 'snow' ? 2 : 4;
      for (var c = 0; c < n; c++) cloud(ctx, Math.round(((tt / 400 + c * (W + 40) / n) % (W + 40)) - 20), top + 8 + (c % 2) * 14 + (c > 1 ? 6 : 0), 0.6);
    }
    if (info.rainbow) rainbowArc(ctx, top, bottom);
    hills(ctx);
    drawWeather(ctx, info.weather, top, bottom, tt, still);
  }
  /* 1.9.1 weather layers. Every colour keeps ink text >= 3:1 (checked by the update audit). */
  var RAIN = '#5a8a28', CLOUDG = '#628f2c';
  function cloud(ctx, x, y, a, col) {
    ctx.fillStyle = col || 'rgba(206,224,110,' + a + ')';             // 1.9.8: a puffy cloud (same 18 x 6 box) on the x5 grid
    fshape(ctx, x, y - 2.4, x + 18, y + 4, function (u, v) { return inCap(u, v, x + 2, y + 1.6, x + 16, y + 1.6, 2.2) || inDisc(u, v, x + 8.6, y + 0.4, 3.2) || inDisc(u, v, x + 5, y + 1, 2.4) || inDisc(u, v, x + 12.4, y + 1, 2.4); });
  }
  function bigCloud(ctx, x, y, col) {
    ctx.fillStyle = col;
    fshape(ctx, x, y - 5, x + 34, y + 6, function (u, v) {             // 1.9.8: a rounded storm cloud (same 34 x 11 box)
      return inCap(u, v, x + 3, y + 2.6, x + 31, y + 2.6, 3.2) || inDisc(u, v, x + 11.5, y - 0.2, 4) || inDisc(u, v, x + 21.5, y - 1.2, 4.6) || inDisc(u, v, x + 28, y + 1.2, 3.2);
    });
  }
  function rainbowArc(ctx, top, bottom) {
    var cx = 44, cy = bottom - 2, bands = ['rgba(206,224,110,0.95)', RAIN, 'rgba(206,224,110,0.95)', 'rgba(139,172,15,0.9)'];
    for (var b = 0; b < bands.length; b++) {
      ctx.fillStyle = bands[b];
      var rad = 34 - b * 2;
      for (var x = -rad; x <= rad; x++) {
        var yy = Math.round(Math.sqrt(rad * rad - x * x));
        if (cy - yy < top + 2) continue;
        ctx.fillRect(cx + x, cy - yy, 1, 2);
      }
    }
  }
  function drawWeather(ctx, w, top, bottom, tt, still) {
    var h = bottom - top, i;
    if (w === 'grey' || w === 'rain' || w === 'drizzle' || w === 'storm') {
      ctx.fillStyle = 'rgba(48,98,48,' + (w === 'storm' ? 0.26 : w === 'rain' ? 0.18 : 0.12) + ')';
      ctx.fillRect(0, top, W, h);
      var nc = w === 'storm' ? 4 : 3;
      for (i = 0; i < nc; i++) bigCloud(ctx, Math.round(((tt / (w === 'storm' ? 160 : 600) + i * (W + 50) / nc) % (W + 50)) - 40), top + 6 + (i % 2) * 7, w === 'grey' ? 'rgba(206,224,110,0.8)' : CLOUDG);
    }
    if (w === 'rain' || w === 'storm' || w === 'drizzle') {
      // clearly falling rain: slanted streaks that drop fast, plus little splashes on the ground
      var drops = w === 'storm' ? 46 : w === 'rain' ? 36 : 22, len = w === 'drizzle' ? 3 : 7, speed = w === 'drizzle' ? 12 : w === 'storm' ? 4 : 6;
      var slant = w === 'storm' ? 2 : 1, fall = h - 16;
      for (i = 0; i < drops; i++) {
        var yo = ((i * 53 + Math.floor(tt / speed)) % fall), x0 = (i * 37 + (i % 3) * 11) % W - Math.floor(yo * slant / 3);
        var xs = ((x0 % W) + W) % W, ys = top + 14 + yo;
        // 2.0.0: a smooth streak on the x5 grid (it was a stair of whole LCD pixels) with a bright rounded glint at its head
        var ex = xs - len * slant / 3, ey = ys + len;
        ctx.fillStyle = RAIN; fshape(ctx, ex - 1, ys - 1, xs + 1, ey + 1, function (u, v) { return inCap(u, v, xs + .5, ys + .5, ex + .5, ey - .5, .42); });
        ctx.fillStyle = 'rgba(206,224,110,1)'; fshape(ctx, ex, ey - 2.4, ex + 2, ey + .4, function (u, v) { return inCap(u, v, ex + 1.15 + slant * .25, ey - 1.6, ex + 1.0, ey - .6, .36); });
      }
      ctx.fillStyle = RAIN;
      if (!still) for (i = 0; i < (w === 'drizzle' ? 3 : 6); i++) {   // splashes: two little droplets jumping out (2.0.0: round, x5 grid)
        var ph = Math.floor(tt / 160 + i * 2) % 4, sx = (i * 61 + Math.floor(tt / 640) * 23) % (W - 8) + 4;
        if (ph < 2) {
          var sd = ph === 0 ? 1.1 : 2.1, sy = bottom - (ph === 0 ? 1.6 : 2.6);
          fshape(ctx, sx - sd - 1, sy - 1, sx + sd + 2, sy + 1.5, function (u, v) { return inDisc(u, v, sx - sd + .5, sy, .55) || inDisc(u, v, sx + sd + .5, sy, .55); });
        }
      }
    }
    if (w === 'storm') {
      // lightning: a flicker every few seconds (never with reduced motion - the bolt just stays drawn faintly)
      var cyc = tt % 5200, flash = !still && (cyc < 90 || (cyc > 180 && cyc < 250));
      if (flash) { ctx.fillStyle = 'rgba(206,224,110,0.55)'; ctx.fillRect(0, top, W, h); }
      if (flash || still) {
        var bx = 60 + (Math.floor(tt / 5200) * 47) % (W - 120), by = top + 12;
        var BOLT = [[0, 0], [-1, 1], [-2, 2], [-2, 3], [-1, 4], [0, 5], [1, 5], [0, 6], [-1, 7], [-2, 8], [-3, 9], [-3, 10]];
        // 1.9.8: a smooth zig-zag bolt on the x5 grid (same path as before), with its dark edge
        var bolt = function (ox, oy) { return function (u, v) { for (var q = 0; q + 1 < BOLT.length; q++) if (inCap(u, v, bx + ox + BOLT[q][0] * 2 + 1, by + oy + BOLT[q][1] * 2 + 1, bx + ox + BOLT[q + 1][0] * 2 + 1, by + oy + BOLT[q + 1][1] * 2 + 1, 1.05 - q * 0.04)) return true; return false; }; };
        if (!still) { ctx.fillStyle = RAIN; fshape(ctx, bx - 8, by - 1, bx + 6, by + 25, bolt(2, 1)); }
        ctx.fillStyle = still ? CLOUDG : 'rgba(206,224,110,1)';
        fshape(ctx, bx - 8, by - 1, bx + 6, by + 24, bolt(0, 0));
      }
    }
    if (w === 'snow') {
      // 2.0.0: a six-armed flake drawn on the x5 grid - a dark halo and bright arms (it was a 5-pixel cross of LCD pixels)
      var flake = function (fx, fy, r) { return function (u, v) { for (var q = 0; q < 3; q++) { var a = q * Math.PI / 3, c = Math.cos(a) * 2.3, d = Math.sin(a) * 2.3; if (inCap(u, v, fx - c, fy - d, fx + c, fy + d, r)) return true; } return false; }; };
      for (i = 0; i < 20; i++) {
        var fy = top + 8 + ((i * 19 + Math.floor(tt / 55)) % (h - 14)) + .5, fx = ((i * 41 + Math.round(4 * Math.sin(tt / 700 + i))) % W + W) % W + .5;
        ctx.fillStyle = RAIN; fshape(ctx, fx - 3.2, fy - 3.2, fx + 3.2, fy + 3.2, flake(fx, fy, .62));
        ctx.fillStyle = 'rgba(206,224,110,1)'; fshape(ctx, fx - 3, fy - 3, fx + 3, fy + 3, flake(fx, fy, .3));
      }
    }
  }
  /* small sparkle around a golden pal (cosmetic) */
  function goldSparkle(ctx, px, y, t) {
    var ph = Math.floor(t / 400) % 3, spots = [[8, 18], [PS - 14, 10], [PS - 6, 46], [4, 52]];
    ctx.fillStyle = C.lite;
    spots.forEach(function (q, i) {
      if ((i + ph) % 3 === 0) return;
      // 2.0.0: a smooth four-point twinkle on the x5 grid (it was a 5-pixel cross of LCD pixels); it pulses with ph
      var x = px + q[0] + .5, yy = y + q[1] + .5, r = (i + ph) % 3 === 1 ? 2.9 : 2.2;
      fshape(ctx, x - r, yy - r, x + r, yy + r, function (u, v) { var a = Math.sqrt(Math.abs(u - x)), b = Math.sqrt(Math.abs(v - yy)); return a + b <= Math.sqrt(r); });
    });
  }
  function drawHome(ctx, app, t, dt) {
    var st = app.state, p = PP.Game.active(st);
    clear(ctx);
    statusBar(ctx, app, t);
    if (!p) {
      F.draw(ctx, 'NO PAL YET', W / 2, 60, C.ink, 2, 'center');
      F.draw(ctx, 'PRESS B FOR AN EGG', W / 2, 90, C.dark, 1, 'center');
      return;
    }
    if (app.anim && t - app.anim.t0 > app.anim.dur) app.anim = null;
    var cx = (W - PS) / 2, y = GROUND - PS;
    if (!p.fate) drawScene(ctx, st, t);
    if (p.stage === 'egg') {
      var left = PP.Evolution.minutesToNextStage(p), fast = left <= 2;
      drawStrip(ctx, p, t);
      drawEgg(ctx, p.species, t, fast, cx, y);
      dotted(ctx, L.floorLine);
      F.draw(ctx, 'HATCHING IN ' + Math.max(1, left) + ' MIN', W / 2, L.bottomText, C.ink, 1, 'center');
      return;
    }
    if (p.fate) {
      if (p.fate === 'dead') {
        S.drawFx(ctx, 'tomb', W / 2 - 24, 52, 3);
        F.draw(ctx, 'R.I.P. ' + p.name.toUpperCase(), W / 2, 108, C.ink, 1, 'center');
        F.draw(ctx, (p.fateCause || '').toUpperCase(), W / 2, 120, C.dark, 1, 'center');
      } else {
        F.draw(ctx, p.name.toUpperCase(), W / 2, 46, C.ink, 2, 'center');
        F.draw(ctx, p.fateCause === 'ran away' ? 'RAN AWAY...' : 'IS GONE', W / 2, 70, C.ink, 1, 'center');
      }
      F.draw(ctx, 'PRESS B', W / 2, L.bottomText, C.dark, 1, 'center');
      return;
    }
    var moving = walkerUpdate(app, p, dt, t), w = app.walker;
    var pf = petPose(p, app, moving, t), pose = pf[0], frame = pf[1];
    var px = Math.round(w.x), flip = w.dir < 0;
    if (p.asleep || p.sick) flip = false;
    // 1.9.1: now and then the pal reacts to its sky - a shiver in rain / snow, a happy hop in the sun
    var react = !moving && !app.anim && !p.asleep && p.lights && !reducedMotion() ? reactionAt(st, t) : null;
    if (react === 'shiver') px += Math.floor(t / 70) % 2 ? 1 : -1;
    else if (react === 'hop') { y -= Math.round(5 * Math.abs(Math.sin((t % 1200) / 1200 * Math.PI * 2))); pose = 'happy'; frame = Math.floor(t / 250); }
    app.reaction = react;
    S.draw(ctx, p.species, S.stageKeyOf(p), pose, frame, px, y, PET, flip);
    if (p.golden && !p.asleep) goldSparkle(ctx, px, y, reducedMotion() ? 0 : t);

    // poop pile (bottom right)
    for (var i = 0; i < p.poop; i++) {
      var pa = poopAt(i); S.drawFx(ctx, Math.floor(t / 500 + i) % 2 ? 'poop' : 'poop2', pa[0], pa[1], 2);
    }
    // mood FX
    var hx = px + (flip ? 4 : PS - 34), hy = y + 10;
    if (p.asleep) S.drawFx(ctx, Math.floor(t / 700) % 2 ? 'zzz' : 'zzz2', px + PS - 30, y - 4 + (Math.floor(t / 700) % 2) * 3, 2);
    else if (p.sick) S.drawFx(ctx, Math.floor(t / 600) % 2 ? 'skull' : 'germ', hx, hy - 12, 2);
    else if (p.fake && !app.anim) S.drawFx(ctx, 'anger', hx, hy - 10 + (Math.floor(t / 300) % 2), 2);
    else if (pose === 'sad' && !app.anim) S.drawFx(ctx, 'sweat', hx, hy, 2);
    if (!app.anim && p.lights) needBubble(ctx, PP.Care.attention(p).filter(function (k) { return k !== 'poop' || p.poop >= 1; }), px, y, flip, t, p.species);

    // action FX
    if (app.anim) drawAnimFx(ctx, app.anim, t, px, y, flip, p.species);

    dotted(ctx, L.floorLine);
    F.draw(ctx, p.name.toUpperCase() + ' ' + (p.sex === 'M' ? '\u2642' : '\u2640'), 3, L.bottomText, C.ink);
    if (p.stage === 'adult') F.draw(ctx, 'LV' + p.level, W - 3, L.bottomText, C.ink, 1, 'right');

    if (!p.lights) {   // lights off: the room goes dark, the status strip stays readable
      var top = L.stripEnd;
      ctx.fillStyle = 'rgba(15,56,15,0.82)'; ctx.fillRect(0, top, W, H - top);
      if (p.asleep) F.draw(ctx, 'Z z z', px + PS / 2, y + 20, C.mid, 1, 'center');
    }
    drawStrip(ctx, p, t);
  }

  function reactionAt(st, t) {
    if (Math.floor(t / 1200) % 12 !== 0) return null;                 // 1.2 s out of every ~14 s
    return PP.Behave.weatherReaction(sceneInfo(st).weather);
  }
  function banner(ctx, msg) {
    var mw = F.width(msg) + 6, my = L.stripEnd + 2;
    ctx.fillStyle = C.ink; ctx.fillRect((W - mw) / 2 - 1, my - 1, mw + 2, 11);
    ctx.fillStyle = C.lite || C.bg; ctx.fillRect((W - mw) / 2, my, mw, 9);
    F.draw(ctx, msg, W / 2, my + 1, C.ink, 1, 'center');
  }
  function drawAnimFx(ctx, a, t, px, y, flip, species) {
    var k = (t - a.t0) / a.dur, fxX = flip ? px - 20 : px + PS - 12, fy = GROUND - 34;
    fxX = Math.max(0, Math.min(W - 32, fxX));
    if (a.kind === 'eat') {
      var fd = PP.DATA.foodOf(species), food = a.food === 'snack' ? 'snack' : (k < 0.45 ? fd.fx : fd.bitten);   // 1.9.9: the pal's own diet
      if (k < 0.85) S.drawFx(ctx, a.food === 'snack' && k > 0.5 ? 'heart' : food, fxX, fy, 2);
    } else if (a.kind === 'look') {        // 2.0.0: a little heart when it smiles at you
      if (t - a.t0 > 900) S.drawFx(ctx, 'heart', px + PS / 2 - 16, y + 2 - Math.min(10, (t - a.t0 - 900) / 60), 2);
    } else if (a.kind === 'happy' || a.kind === 'praise') {
      for (var i = 0; i < 3; i++) {
        var hk = (k * 2 + i / 3) % 1;
        S.drawFx(ctx, i === 1 ? 'note' : 'heart', px + 10 + i * 28, y + 20 - hk * 40, 2);
      }
    } else if (a.kind === 'med') {
      S.drawFx(ctx, 'pill', fxX + (1 - Math.min(1, k * 2)) * 20 * (flip ? -1 : 1), fy - 20, 2);
    } else if (a.kind === 'angry' || a.kind === 'scold') {
      S.drawFx(ctx, 'anger', px + PS / 2 - 16, y + 4 + (Math.floor(t / 150) % 2) * 2, 2);
    } else if (a.kind === 'refuse') {
      S.drawFx(ctx, a.food === 'snack' ? 'snack' : PP.DATA.foodOf(species).fx, fxX, fy, 2);
    } else if (a.kind === 'tired') {     // one-line message on the LCD, gone with the animation
      S.drawFx(ctx, Math.floor(t / 500) % 2 ? 'zzz' : 'zzz2', px + (flip ? 4 : PS - 30), y - 2, 2);
      var msg = 'TOO TIRED...', mw = F.width(msg) + 6, my = L.stripEnd + 2;
      ctx.fillStyle = C.ink; ctx.fillRect((W - mw) / 2 - 1, my - 1, mw + 2, 11);
      ctx.fillStyle = C.lite || C.bg; ctx.fillRect((W - mw) / 2, my, mw, 9);
      F.draw(ctx, msg, W / 2, my + 1, C.ink, 1, 'center');
    } else if (a.kind === 'wake') {       // 1.9.1 good morning banner + a note at the stretch
      banner(ctx, a.text || 'FEELING REFRESHED!');   // 1.9.9: set by App.wakeUp (nap line, or the greeting for the hour)
      if (t - a.t0 > 1900) S.drawFx(ctx, 'note', px + (flip ? 4 : PS - 30), y + 2 - k * 10, 2);
    } else if (a.kind === 'stillAsleep') { // 1.9.1 lights on in sleep hours: say so on the LCD
      banner(ctx, a.text || 'STILL ASLEEP');
    } else if (a.kind === 'dance') {
      S.drawFx(ctx, 'note', px + (Math.floor(t / 260) % 2 ? 6 : PS - 30), y + 2 - k * 12, 2);
    } else if (a.kind === 'sad' || a.kind === 'no') {
      S.drawFx(ctx, 'sweat', px + (flip ? 8 : PS - 36), y + 18 + k * 8, 2);
    } else if (a.kind === 'clean') {
      var bx = W - k * 1.6 * W;
      var ct = L.stripEnd;
      ctx.fillStyle = C.ink; ctx.fillRect(Math.round(bx), ct, 4, L.floorLine - ct);
      ctx.fillStyle = C.dark; ctx.fillRect(Math.round(bx) + 5, ct, 2, L.floorLine - ct);
    } else if (a.kind === 'sick') {
      S.drawFx(ctx, 'germ', px + PS / 2, y + 6, 2);
    } else if (a.kind === 'level') {
      S.drawFx(ctx, 'star', px + PS / 2 - 16, y - 4 - k * 20, 2);
    } else if (a.kind === 'cup') {        // 1.8.4 cup-cleared celebration: stars burst round the pal + a banner
      for (var si = 0; si < 5; si++) {
        var ang = si / 5 * Math.PI * 2 + k * 5, rr = 20 + 26 * ((k * 3 + si / 5) % 1);
        S.drawFx(ctx, 'star', Math.round(px + PS / 2 - 8 + Math.cos(ang) * rr * 1.4), Math.round(y + PS / 2 - 18 + Math.sin(ang) * rr * 0.7), 1);
      }
      var cm = (a.text || 'CUP CLEARED!'), cw = F.width(cm) + 8, cy = L.stripEnd + 2;
      if (Math.floor(t / 300) % 4 !== 3 || k > 0.8) {
        ctx.fillStyle = C.ink; ctx.fillRect((W - cw) / 2 - 1, cy - 1, cw + 2, 11);
        ctx.fillStyle = C.lite || C.bg; ctx.fillRect((W - cw) / 2, cy, cw, 9);
        F.draw(ctx, cm, W / 2, cy + 1, C.ink, 1, 'center');
      }
    }
  }

  /* ------------------------------------------------------------ cut-scenes */
  function drawCut(ctx, app, t) {
    var c = app.cut, k = t - c.t0, cx = (W - PS) / 2, y = GROUND - PS - 6;
    clear(ctx);
    if (c.kind === 'evolve') {
      var swapAt = 2800;
      if (k < swapAt) {
        var period = Math.max(50, 420 - k * 0.14), showNew = Math.floor(k / period) % 2 === 1;
        S.draw(ctx, c.species, showNew ? c.toKey : c.fromKey, 'idle', 0, cx, y, PET);
        F.draw(ctx, c.secret && k > 1400 ? '?!?!' : 'WHAT?!', W / 2, 16, C.ink, 2, 'center');
        if (c.secret && k > 1400) {                         // 1.9.7 secret form: the screen pulses dark before the reveal
          ctx.save(); ctx.globalAlpha = 0.18 + 0.12 * Math.sin(k / 90); ctx.fillStyle = C.dark; ctx.fillRect(0, 0, W, H); ctx.restore();
        }
        for (var i = 0; i < 6; i++) {
          var ang = k / 300 + i * Math.PI / 3, r = 70 - k / 60;
          S.drawFx(ctx, 'star', W / 2 - 8 + Math.cos(ang) * r, 90 + Math.sin(ang) * r * 0.6, 1);
        }
      } else {
        if (k < swapAt + 160) { clear(ctx, C.lite); return; }
        if (c.secret) {                                      // 1.9.7: a ring of light rays behind a secret form
          // 2.0.0: crisp rays on the x5 grid in the LCD tone (they were blurry anti-aliased canvas strokes)
          ctx.fillStyle = C.dark;
          for (var q = 0; q < 12; q++) {
            var aq = q * Math.PI / 6 + (k - swapAt) / 900, r0 = 34, r1 = 34 + Math.min(70, (k - swapAt) / 12);
            var ax = W / 2 + Math.cos(aq) * r0, ay = 96 + Math.sin(aq) * r0 * .7, bx2 = W / 2 + Math.cos(aq) * r1, by2 = 96 + Math.sin(aq) * r1 * .7;
            fshape(ctx, Math.min(ax, bx2) - 2, Math.min(ay, by2) - 2, Math.max(ax, bx2) + 2, Math.max(ay, by2) + 2, (function (ax, ay, bx2, by2) { return function (u, v) { return inCap(u, v, ax, ay, bx2, by2, 1.5); }; })(ax, ay, bx2, by2));
          }
        }
        var kk = k - swapAt;   // reveal: jump for joy, then show off the species habit
        S.draw(ctx, c.species, c.toKey, kk < 1200 ? 'happy' : 'quirk', kk < 1200 ? Math.floor(k / 250) : Math.floor((kk - 1200) / 300), cx, y, PET);
        for (var j = 0; j < 8; j++) {
          var a2 = j * Math.PI / 4, r2 = 30 + (k - swapAt) / 25;
          if (r2 < 130) S.drawFx(ctx, j % 2 ? 'star' : 'spark', W / 2 - 8 + Math.cos(a2) * r2, 96 + Math.sin(a2) * r2 * 0.6, 1);
        }
        F.draw(ctx, c.secret ? 'A SECRET FORM!' : 'EVOLVED INTO', W / 2, 6, C.ink, 1, 'center');
        F.draw(ctx, c.name.toUpperCase(), W / 2, 17, C.ink, 2, 'center');
        if (c.sub) F.draw(ctx, c.sub.toUpperCase(), W / 2, L.bottomText, C.dark, 1, 'center');
      }
    } else if (c.kind === 'hatch') {
      if (k < 1600) {
        if (k > 1000) S.draw(ctx, c.species, 'egg', 'happy', Math.floor(k / 150) % 2, cx, y + 6, PET);   // cracking
        else drawEgg(ctx, c.species, k, true, cx, y + 6);
        F.draw(ctx, '...!', W / 2, 20, C.ink, 2, 'center');
      } else if (k < 1760) { clear(ctx, C.lite); }
      else {
        S.draw(ctx, c.species, 'baby', 'happy', Math.floor(k / 250), cx, y + 6, PET);
        F.draw(ctx, 'HATCHED!', W / 2, 10, C.ink, 2, 'center');
        F.draw(ctx, c.name.toUpperCase() + ' THE ' + PP.DATA.NAMES[c.species].baby.toUpperCase(), W / 2, L.bottomText, C.dark, 1, 'center');
      }
    } else if (c.kind === 'die') {
      if (k < 1500) S.draw(ctx, c.species, c.key, 'faint', Math.floor(k / 400), cx, y + 6, PET);
      else S.drawFx(ctx, 'tomb', W / 2 - 24, 64, 3);
      F.draw(ctx, c.title, W / 2, 16, C.ink, 1, 'center');
    }
  }
  function cutDuration(c) { return c.kind === 'evolve' ? (c.secret ? 6400 : 5200) : c.kind === 'hatch' ? 3600 : 3200; }

  PP.Render = { W: W, H: H, DPR: DPR, GROUND: GROUND, PET: PET, C: C, LAYOUT: L, clear: clear, fshape: fshape, inCap: inCap, inDisc: inDisc, drawHome: drawHome, drawCut: drawCut, cutDuration: cutDuration,
    statusBar: statusBar, drawEgg: drawEgg, stripBoxes: stripBoxes, stageAge: stageAge, MINI: MINI, mini: mini, poopAt: poopAt,
    sceneInfo: sceneInfo, drawScene: drawScene, forceScene: function (v) { sceneForce = v || null; } };
})(typeof window !== 'undefined' ? window : globalThis);
